#!/bin/bash 

curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &
curl -XPOST 'http://localhost:8080/redis-test/users/1' &

curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
curl -XPOST 'http://localhost:8090/redis-test/users/1' &
