
#!/bin/bash 

curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
curl -XPOST 'http://localhost:8080/redis-test/users/1/lock' &
